CREATE DATABASE homelane;

USE homelane;

CREATE TABLE `NOTES` (
	`ID`			INT NOT NULL AUTO_INCREMENT,
    `NOTE_TITLE`	VARCHAR(50) NOT NULL,
    `NOTE_TEXT`		VARCHAR(5000) NOT NULL,
    `CREATE_TIME`	TIMESTAMP NOT NULL,
    `IMPORTANCE`	ENUM('High', 'Medium', 'Low'),
    `COLOR_CODE`	VARCHAR(10),
    PRIMARY KEY (`ID`)
);
